---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: training-advisor-build
    type: builder
    artifact_dir: ./
    build_type: grunt
    script: |-
      #!/bin/bash
      # Install RVM, Ruby, and SASS
      # Needed when running grunt build
      gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
      curl -sSL https://get.rvm.io | bash -s stable --ruby --gems=sass
      # Start RVM
      source /home/jenkins/.rvm/scripts/rvm
      # Build training-advisor
      npm install
      grunt build
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: training-advisor-build
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push
      # view logs
      #cf logs "${CF_APP}" --recent
